-- Tabla opcional para guardar resultados del prototipo Zombies Lunares.
-- Ejecuta este SQL en Supabase SQL Editor si quieres activar el guardado de partidas.

create table if not exists public.zombies_lunares_runs (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  outcome text not null check (outcome in ('victory', 'defeat')),
  saved_count integer not null check (saved_count >= 0),
  lost_count integer not null check (lost_count >= 0),
  total_zombies integer not null check (total_zombies > 0),
  target_saved integer not null check (target_saved > 0),
  elapsed_seconds integer not null check (elapsed_seconds >= 0)
);

alter table public.zombies_lunares_runs enable row level security;

create policy "Anyone can insert Zombies Lunares runs"
  on public.zombies_lunares_runs
  for insert
  to anon, authenticated
  with check (true);

create policy "Anyone can read Zombies Lunares runs"
  on public.zombies_lunares_runs
  for select
  to anon, authenticated
  using (true);
